name: fundee
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cloud_firestore: ^0.13.5
  flutter:
    sdk: flutter
  simple_animations: ^1.3.3
  curved_navigation_bar: ^0.1.2 #latest version

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cached_network_image: ^2.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/button.png
   - assets/images/DentalChart(Adult).png
   - assets/images/ToothLogo.png
   - assets/images/ToothNo1.png
   - assets/images/patient.png
  #  - assets/images/tooth1-1.png
  #  - assets/images/tooth1-2.png
  #  - assets/images/tooth1-3.png
   - assets/images/Fun-D-Logo-(Blue-New).png
   - assets/images/Fun-D-Logo-(White-New).png
   - images/tooth/AllGum.png
   - images/tooth/1-lastest.png
   - images/tooth/2-lastest.png
   - images/tooth/3-lastest.png
   - images/tooth/4-lastest.png
   - images/tooth/5-lastest.png
   - images/tooth/6-lastest.png
   - images/tooth/7-lastest.png
   - images/tooth/8-lastest.png
   - images/tooth/9-lastest.png
   - images/tooth/10-lastest.png
   - images/tooth/11-lastest.png
   - images/tooth/12-lastest.png
   - images/tooth/13-lastest.png
   - images/tooth/14-lastest.png
   - images/tooth/15-lastest.png
   - images/tooth/16-lastest.png
   - images/tooth/17-lastest.png
   - images/tooth/18-lastest.png
   - images/tooth/19-lastest.png
   - images/tooth/20-lastest.png
   - images/tooth/21-lastest.png
   - images/tooth/22-lastest.png
   - images/tooth/23-lastest.png
   - images/tooth/24-lastest.png
   - images/tooth/25-lastest.png
   - images/tooth/26-lastest.png
   - images/tooth/27-lastest.png
   - images/tooth/28-lastest.png
   - images/tooth/29-lastest.png
   - images/tooth/30-lastest.png
   - images/tooth/31-lastest.png
   - images/tooth/32-lastest.png

   #  - assets/images/a_dot_ham.jpeg  


   - images/tooth/detail/1-1.png
   - images/tooth/detail/1-2.png
   - images/tooth/detail/1-3.png
   - images/tooth/detail/2-1.png
   - images/tooth/detail/2-2.png
   - images/tooth/detail/2-3.png
   - images/tooth/detail/3-1.png
   - images/tooth/detail/3-2.png
   - images/tooth/detail/3-3.png
   - images/tooth/detail/4-1.png
   - images/tooth/detail/4-2.png
   - images/tooth/detail/4-3.png
   - images/tooth/detail/5-1.png
   - images/tooth/detail/5-2.png
   - images/tooth/detail/5-3.png
   - images/tooth/detail/6-1.png
   - images/tooth/detail/6-2.png
   - images/tooth/detail/6-3.png
   - images/tooth/detail/7-1.png
   - images/tooth/detail/7-2.png
   - images/tooth/detail/7-3.png
   - images/tooth/detail/8-1.png
   - images/tooth/detail/8-2.png
   - images/tooth/detail/8-3.png
   - images/tooth/detail/9-1.png
   - images/tooth/detail/9-2.png
   - images/tooth/detail/9-3.png
   - images/tooth/detail/10-1.png
   - images/tooth/detail/10-2.png
   - images/tooth/detail/10-3.png
   - images/tooth/detail/11-1.png
   - images/tooth/detail/11-2.png
   - images/tooth/detail/11-3.png
   - images/tooth/detail/12-1.png
   - images/tooth/detail/12-2.png
   - images/tooth/detail/12-3.png
   - images/tooth/detail/13-1.png
   - images/tooth/detail/13-2.png
   - images/tooth/detail/13-3.png
   - images/tooth/detail/14-1.png
   - images/tooth/detail/14-2.png
   - images/tooth/detail/14-3.png
   - images/tooth/detail/15-1.png
   - images/tooth/detail/15-2.png
   - images/tooth/detail/15-3.png
   - images/tooth/detail/16-1.png
   - images/tooth/detail/16-2.png
   - images/tooth/detail/16-3.png
   - images/tooth/detail/17-1.png
   - images/tooth/detail/17-2.png
   - images/tooth/detail/17-3.png
   - images/tooth/detail/18-1.png
   - images/tooth/detail/18-2.png
   - images/tooth/detail/18-3.png
   - images/tooth/detail/19-1.png
   - images/tooth/detail/19-2.png
   - images/tooth/detail/19-3.png
   - images/tooth/detail/20-1.png
   - images/tooth/detail/20-2.png
   - images/tooth/detail/20-3.png
   - images/tooth/detail/21-1.png
   - images/tooth/detail/21-2.png
   - images/tooth/detail/21-3.png
   - images/tooth/detail/22-1.png
   - images/tooth/detail/22-2.png
   - images/tooth/detail/22-3.png
   - images/tooth/detail/23-1.png
   - images/tooth/detail/23-2.png
   - images/tooth/detail/23-3.png
   - images/tooth/detail/24-1.png
   - images/tooth/detail/24-2.png
   - images/tooth/detail/24-3.png
   - images/tooth/detail/25-1.png
   - images/tooth/detail/25-2.png
   - images/tooth/detail/25-3.png
   - images/tooth/detail/26-1.png
   - images/tooth/detail/26-2.png
   - images/tooth/detail/26-3.png
   - images/tooth/detail/27-1.png
   - images/tooth/detail/27-2.png
   - images/tooth/detail/27-3.png
   - images/tooth/detail/28-1.png
   - images/tooth/detail/28-2.png
   - images/tooth/detail/28-3.png
   - images/tooth/detail/29-1.png
   - images/tooth/detail/29-2.png
   - images/tooth/detail/29-3.png
   - images/tooth/detail/30-1.png
   - images/tooth/detail/30-2.png
   - images/tooth/detail/30-3.png
   - images/tooth/detail/31-1.png
   - images/tooth/detail/31-2.png
   - images/tooth/detail/31-3.png
   - images/tooth/detail/32-1.png
   - images/tooth/detail/32-2.png
   - images/tooth/detail/32-3.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Kanit-Regular.ttf
        - asset: fonts/Kanit-Italic.ttf
          style: italic
        - asset: fonts/Kanit-Bold.ttf
          weight: 700
        - asset: fonts/Kanit-SemiBold.ttf
          weight: 600
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
